modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]]
modId="mush"
version="1.0.0"
displayName="Mush"
credits="Rellit"
authors="Rellit"
description='''
This mod adds sleds powered by wolves!
'''